# Generated by Django 5.1.6 on 2025-02-20 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("InventoryManagementApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventoryitem",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="name",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="user",
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="brand",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="code",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="size",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="type",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="InventoryManagementApp.category",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
